// <auto-generated />
using System;
using Last_version_of_school_management_system.Models.Mymodels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Last_version_of_school_management_system.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("Min_degree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<int>("instructor_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dept_id");

                    b.HasIndex("instructor_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Manger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Instructors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<int?>("deptartment_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("deptartment_id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Courses", b =>
                {
                    b.HasOne("Last_version_of_school_management_system.Models.Mymodels.Departments", "Departments")
                        .WithMany("courses")
                        .HasForeignKey("dept_id");

                    b.HasOne("Last_version_of_school_management_system.Models.Mymodels.Instructors", "Instructor")
                        .WithMany("course")
                        .HasForeignKey("instructor_id")
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Instructors", b =>
                {
                    b.HasOne("Last_version_of_school_management_system.Models.Mymodels.Departments", "department")
                        .WithMany("instructor")
                        .HasForeignKey("deptartment_id");

                    b.Navigation("department");
                });

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Departments", b =>
                {
                    b.Navigation("courses");

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("Last_version_of_school_management_system.Models.Mymodels.Instructors", b =>
                {
                    b.Navigation("course");
                });
#pragma warning restore 612, 618
        }
    }
}
